services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-online-shop
    environment:
        MYSQL_ROOT_PASSWORD: mysql
        MYSQL_DATABASE: online_shop_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: